// <auto-generated />
using GoldbergGUI.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldbergGUI.Core.Migrations
{
    [DbContext(typeof(SteamDbContext))]
    partial class SteamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("GoldbergGUI.Core.Models.SteamApp", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("appid")
                        .HasJsonPropertyName("appid");

                    b.Property<string>("AppType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("ComparableName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("comparable_name");

                    b.Property<long>("LastModified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_modified")
                        .HasJsonPropertyName("last_modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<long>("PriceChangeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price_change_number")
                        .HasJsonPropertyName("price_change_number");

                    b.HasKey("AppId");

                    b.HasIndex("AppType");

                    b.HasIndex("ComparableName");

                    b.ToTable("steamapp", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
